#!/bin/sh
# (1) Отключаем IPv6 на всех уровнях
uci set network.lan.ip6assign='0'
uci set dhcp.lan.ra='disabled'
uci set dhcp.lan.dhcpv6='disabled'
uci set dhcp.lan.ndp='disabled'
uci set dhcp.lan.ra_management='0'
# Отключаем odhcpd entirely
uci set dhcp.@odhcpd[0].ra='disabled'
uci set dhcp.@odhcpd[0].dhcpv6='disabled'
uci set dhcp.@odhcpd[0].ndp='disabled'

# Добавляем sysctl-параметры
uci add_list system.@system[0].sysctl='net.ipv6.conf.all.disable_ipv6=1'
uci add_list system.@system[0].sysctl='net.ipv6.conf.default.disable_ipv6=1'
uci add_list system.@system[0].sysctl='net.ipv6.conf.lo.disable_ipv6=1'
uci add_list system.@system[0].sysctl='net.ipv6.conf.eth0.disable_ipv6=1'
uci add_list system.@system[0].sysctl='net.ipv6.conf.br-lan.disable_ipv6=1'
uci add_list system.@system[0].sysctl='net.ipv6.conf.all.forwarding=0'

# (2) TTL-спуфинг: дополняем /etc/firewall.user
cat << 'EOF' >> /etc/firewall.user
# === TTL spoofing by HELIOS ===
# +1 для пакетов из LAN
iptables -t mangle -A PREROUTING -i br-lan -j TTL --ttl-inc 1
# TTL=64 для исходящих в WAN
iptables -t mangle -A POSTROUTING -o eth0.2 -j TTL --ttl-set 64
EOF

# Commit & cleanup
uci commit network
uci commit dhcp
uci commit system

# Применяем сразу (без перезагрузки)
/etc/init.d/network reload
/etc/init.d/odhcpd stop
/etc/init.d/firewall restart
/etc/init.d/dnsmasq restart

# Удаляем скрипт, чтобы не выполнялся повторно
rm -f /etc/uci-defaults/50-custom
